name: Run python script after push

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Python script
        run: python hello_world.py
